@extends('layouts.pdf')

@section('content')
<style>
    body { font-family: DejaVu Sans, Arial, sans-serif; }
    .credit-header { background: #f8d7da; padding: 20px; border-bottom: 4px solid #dc3545; }
    .credit-title { color: #721c24; font-size: 1.5rem; font-weight: bold; }
    .credit-sub { color: #721c24; }
    .note-body { padding: 20px; }
    .amount { font-size: 2rem; color: #dc3545; font-weight: 700; }
</style>

<div class="credit-header">
    <div class="credit-title">CREDIT NOTE</div>
    <div class="credit-sub">Policy File: {{ $policy->fileno }} — {{ $policy->policy_no ?? '' }}</div>
</div>

<div class="note-body">
    <p><strong>Customer:</strong> {{ $policy->customer_name }}</p>
    <p><strong>Insurer:</strong> {{ $policy->insurer_name }}</p>

    <hr>

    <p><strong>Total Credit Amount:</strong></p>
    <div class="amount">KES {{ number_format(abs($policy->premium ?? 0), 2) }}</div>

    <p>Details:</p>
    <ul>
        <li>Sum Insured: KES {{ number_format(abs($policy->sum_insured ?? 0), 2) }}</li>
        <li>Premium: KES {{ number_format(abs($policy->premium ?? 0), 2) }}</li>
        <li>Net Premium: KES {{ number_format(abs($policy->net_premium ?? 0), 2) }}</li>
    </ul>

    <p class="small text-muted">This credit note was generated by the system on {{ \Carbon\Carbon::now()->format('d-m-Y') }}.</p>
</div>
@endsection